### ISSUE TITLE
cannot access core python modules

### ISSUE THREAD

**Issue by chris-aeviator** [JSH32/PySandbox#1]
I'm trying to use core libraries like httplib2, json. However, the sandbox cannot access them. I made sure to have rustpython --install-pip , also I'm partly able to install modules with rustpython -m pip install simplejson , however the sandbox does not find them

Evalresult(stdout=Stdout(out='', err='Traceback (most recent call last):\n  File "<embedded>", line 1, in <module>\n  File "<embedded>", line 6, in hello\nModuleNotFoundError: No module named \'urllib2\'\n'), value=None)
> from wasm_py_sandbox import create_sandbox
> sandbox = create_sandbox()
> stdout = sandbox.exec("""
> def hello(x):
>     # import requests
>     # reply = requests.post('http://httpbin.io/post', json={"func_name": "find_berufsbilder"})
>     import urllib2
>     import json
> 
>     data = {
>             'ids': [12, 3, 4, 5, 6]
>     }
> 
>     req = urllib2.Request('http://httpbin.io/post')
>     req.add_header('Content-Type', 'application/json')
> 
>     response = urllib2.urlopen(req, json.dumps(data))
>     return response
> """)
> 
> result = sandbox.eval("hello(1)")
> print(result)

**Comment by JSH32** [comment]
The sandbox currently was designed to make a fully safe and sandboxed way to run python code for a CS class autograder. It isn't supposed to have net/io access for that reason, especially considering it does so by running in WASM (where RustPython doesn't have as many features), *however*, I can make an interface for creating python objects/functions and passing them into the sandbox either as an importable module or a global. Would that help your case?

If you need full sandboxing *and* all features and pip then you might need to run this in a Docker container with IPC or something to communicate back and forth, or Firecracker VM

**Comment by chris-aeviator** [comment]
> re: interface
yes, passing context is a good start.

it would be super useful to be able to control what's allowed & what's not. I'll review firecracker, as long as it's drop in that'll work, but I found it quite useful to be pure python.

My code runs with rustpython btw.

❯ rustpython test.py
{
  "args": {},
  "data": "{\"key1\": \"value1\", \"key2\": \"value2\", \"key3\": \"value3\"}",
  "files": {},
  "form": {},
  "headers": {
    "Accept-Encoding": "identity",
    "Content-Length": "54",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "Python-urllib/3.10",
    "X-Amzn-Trace-Id": "Root=1-65b007bd-1ad8802f24391c1e01ef13ab"
  },
  "json": {
    "key1": "value1",
    "key2": "value2",
    "key3": "value3"
  },
  "origin": "xxxxxxxxx",
  "url": "https://httpbin.org/post"
}

**Comment by JSH32** [comment]
RustPython and RustPython in WASM have different supported features. RustPython is not sandboxed or safe while RustPython in WASM is, which is why it's compiled to WASM and uses WAI for interfacing

**Comment by chris-aeviator** [comment]
understood - what I don't understand  is how to controll permissions around io/ netio etc. when importing a module that'll need it.

**Comment by JSH32** [comment]
I don't actually think net/io is supported by rustpython when compiled to WASM/WASI target, my recommendation is to use Docker or firecracker and control network/resources through that. I assume you know what docker is, and firecracker is a VM backend built by AWS which is designed to have a super fast startup time and low resource usage, it's used for AWS lambda.

**Comment by chris-aeviator** [comment]
Thanks - I’m went onto  firecracker already today, still like the idea of packaging this as beautifully as in your lib.
Will check out rustpython wasm functionalities later this week.

**Comment by JSH32** [comment]
I'll leave this open for now, let me know if you find a way to do this thru RustPython WASM or a potential alternative.
